name: zero2prod
services:
  webapi:
    build: .
    container_name: zero2prod-api
    hostname: zero2prod
    ports:
      - 8000:8000
    depends_on:
      - database
    links:
      - "database:postgres"
    environment:
      - "APP_DATABASE__USERNAME=root"
      - "APP_DATABASE__PASSWORD=yourStrong(!)Password"
      - "APP_DATABASE__HOST=postgres"
      - "APP_DATABASE__PORT=5432"
      - "APP_DATABASE__DATABASE_NAME=newsletter"

  database:
    image: postgres:latest
    container_name: database
    hostname: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: yourStrong(!)Password
      POSTGRES_DB: root
    ports:
      - 5432:5432
