name: zero2prod
services:
  webapi:
    build: .
    container_name: zero2prod-api
    hostname: zero2prod
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      APP_DATABASE__HOST: postgres
      APP_DATABASE__REQUIRE_SSL: false
    networks:
      - zero2prod

  database:
    image: postgres:latest
    container_name: postgres-db
    hostname: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: yourStrong(!)Password
      POSTGRES_DB: root
    ports:
      - 5432:5432
    networks:
      - zero2prod

networks:
  zero2prod:
    driver: bridge
