name: Zero To Production CI
run-name: ${{github.actor}} running Continous Integration
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - 'main'

jobs:
  running-tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: yourStrong(!)Password
          POSTGRES_DB: root
        ports:
          - 5432:5432
    steps:
      - name: Checkout Projects
        uses: actions/checkout@v4

      - name: Setup Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install SQLx and Setup Database
        run: |
          cargo install --version='~0.7' sqlx-cli --no-default-features --features rustls,postgres
          chmod +x ./scripts/init_db.sh && SKIP_DOCKER=true ./scripts/init_db.sh

      - name: Check SQLx query metatada is up-to-date
        run: |
          cargo sqlx prepare --workspace --check

      - name: Run Cargo Test   
        run: | 
          export TEST_LOG=true
          cargo test
